version: 2.1
orbs:
  node: circleci/node@3.0.1
  prometheus: prometheus/prometheus@0.11.0
jobs:
  build-lib:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - lib
  build-app:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build-app
  lint-lib:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  test-lib:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm test
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run: npm publish ~/project/lib --access public
workflows:
  version: 2
  test-deploy:
    jobs:
      - build-lib:
          filters:
            tags:
              only: /.*/
      - build-app:
          filters:
            tags:
              ignore: /.*/
      - lint-lib:
          requires:
            - build-lib
          filters:
            tags:
              ignore: /.*/
      - test-lib:
          requires:
            - build-lib
          filters:
            tags:
              ignore: /.*/
      - publish:
          requires:
            - build-lib
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
